name: build
on:
  push:
    branches:
      - main
      - /refs/heads/main

jobs:

  cloud:
    strategy:
      matrix:
        stack:
          - blueprint-golang

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: fogfish/spawner-cdk@main
        with:
          go-version: 1.18
          stack: ${{ matrix.stack }}
          version: latest
          issue-to-create: ./.github/issue-spawn-latest.md
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
