name: carry
on:
  release:
    types: [published]

jobs:
  it:
    strategy:
      matrix:
        stack:
          - blueprint-golang

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1

      - id: deploy
        uses: fogfish/deploy-cdk-go@latest
        with:
          go-version: "1.21"
          stack: ${{ matrix.stack }}
          version: ${{ github.event.release.name }}
          issue-to-create: ./.github/issue-spawn-release.md
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: assay-it/github-actions-quality-check@latest
        with:
          install-go: false
          system-under-test: ${{ steps.deploy.outputs.deployed-api }}
