##
## Quality checks
##
name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  code:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
