##
## Unit Tests & Coverage
##
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main
      - /refs/heads/main

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
     
      - name: go build
        run: |
          go build ./...

      - name: go test
        run: |
          go test -v -coverprofile=profile.cov $(go list ./... | grep -v /examples/)
        env:
          GOPATH: /home/runner/go
          # GOCACHE="/home/runner/.cache/go-build"


          # GOCACHE: ${{ env.GOCACHE }}
          # GOENV: "/home/runner/.config/go/env"
          # GOMODCACHE: "/home/runner/go/pkg/mod"
          # /home/runner/go
          
          # GOROOT: ${{ env.GOROOT }}
          # GOROOT: "/opt/hostedtoolcache/go/1.18.3/x64"
          # GOTOOLDIR: "/opt/hostedtoolcache/go/1.18.3/x64/pkg/tool/linux_amd64"
          # GOMOD: "/home/runner/work/blueprint-serverless-golang/blueprint-serverless-golang/go.mod"

          ## GOPATH required to build serverless app inside unittest
          # GOPATH: ${{ steps.setup.outputs.GOPATH }}
          # GOPATH: /home/runner/go 
          # GOPATH: /home/runner/work/${{ github.event.repository.name }}/go

      - uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: profile.cov
