##
## Clean Sandbox of Pull Request
##
name: clean
on:
  pull_request:
    types:
      - closed

jobs:
  it:
    strategy:
      matrix:
        stack:
          - blueprint-golang

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: fogfish/deploy-cdk-go@latest
        with:
          go-version: 1.18
          command: destroy
          stack: ${{ matrix.stack }}
          version: pr${{ github.event.number }}
          issue-to-comment: ${{ github.event.number }}
          issue-to-create: ./.github/issue-clean-sandbox.md
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
