##
## Clean Sandbox of Pull Request
##
name: clean
on:
  pull_request:
    types:
      - closed

jobs:
  it:
    strategy:
      matrix:
        stack: [blueprint-golang]
    runs-on: ubuntu-latest
    steps:

      ##
      ## setup environment
      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v2

      ##
      ## fetch deps
      - name: go get tools
        run: |
          npm install -g aws-cdk

      ##
      ## destroy application from aws
      - name: aws access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
  
      - name: cdk destroy
        run: |
          cdk destroy -f ${{ matrix.stack }}-pr${{ github.event.number }} \
            -c vsn=pr${{ github.event.number }}
        env:
          GOPATH: /home/runner/work/${{ github.event.repository.name }}/go

      - uses: thollander/actions-comment-pull-request@v1
        with:
          message: '**sandbox** #${{ github.event.number }} is destroyed successfully.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
